title: climate in focus
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://example.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Website
      category: Front end
      description: cif.media, our frontend site
      partial: ""
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#fff"
  enableLastMod: true
  headerTextColor: white
  logo: /img/cif-google.jpg
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - closed: true
      name: Front end
      untitled: false
      description: ""
  description: "we continuously monitor the status of our sites and services and
    if there are any interruptions, we'll let you know here. "
  enableCustomHTML: true
  useLargeHeaderDesign: false
